# Generated by Django 4.2.7 on 2026-02-13 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="معرف الجهاز"
                    ),
                ),
                (
                    "last_sync_timestamp",
                    models.DateTimeField(verbose_name="آخر وقت مزامنة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سجل المزامنة",
                "verbose_name_plural": "سجلات المزامنة",
                "db_table": "sync_logs",
                "ordering": ["-last_sync_timestamp"],
            },
        ),
    ]
