# Generated by Django 4.2.7 on 2026-02-13 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_sync_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sync_status",
        ),
    ]
