# Generated by Django 4.2.7 on 2026-02-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sync_status",
            field=models.CharField(
                blank=True,
                default="synced",
                max_length=20,
                null=True,
                verbose_name="حالة المزامنة",
            ),
        ),
    ]
